version: '3'

services:
  web:
    image: nginx:1.14.2-alpine
    ports:
      - "8088:80"
    volumes: 
      - ./code:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7.1-fpm-alpine
    volumes:
      - ./code:/var/www

